In [123]:
import pandas as pd
import numpy as np

# Importar base do sistema:

In [124]:
arquivo = pd.read_excel(r'C:\Users\L_SAR\Documents\Desenv\notas\base_alterdata_original.xlsx')

# Selecionando as colunas que serão utilizadas:
base_sistema = arquivo[['Nr. nota', 'Dt. emissão', 'Pessoa', 'CPF / CNPJ', 'Vl. faturamento', 'Emp. venda (Nm)', 'Emp. venda (nome curto)']]

# Apagando linhas em branco ou linhas de totais:
base_sistema = base_sistema.dropna(subset = ['Nr. nota'])


# Renomeando os campos para o padrão:
base_sistema = base_sistema.rename(columns = {'Nr. nota' : 'Nota'})
base_sistema = base_sistema.rename(columns = {'Dt. emissão' : 'Data'})
base_sistema = base_sistema.rename(columns = {'Pessoa' : 'Tomador'})
base_sistema = base_sistema.rename(columns = {'CPF / CNPJ' : 'CNPJ_CPF_Tomador'})
base_sistema = base_sistema.rename(columns = {'Vl. faturamento' : 'Valor'})
base_sistema = base_sistema.rename(columns = {'Emp. venda (Nm)' : 'Empresa'})
base_sistema = base_sistema.rename(columns = {'Emp. venda (nome curto)' : 'Unidade'})

# Convertendo tipos de campos:
#base_sistema['Nota'] = base_sistema['Nota'].astype(int)
base_sistema["Nota"] = base_sistema["Nota"].apply(np.int64)

# Valor total para verificar integridade do dataframe:
faturamento_base_sistema = base_sistema['Valor'].sum()

display(base_sistema)

print(faturamento_base_sistema)

base_sistema.dtypes

,Nota,Data,Tomador,CNPJ_CPF_Tomador,Valor,Empresa,Unidade
0,16385,01/07/2022,MARIA CLARA ROSENO DA SILVA (113523) ...,103.254.424-44,71.30,TRANSGUARD DO BRASIL REMOCAO E ACAUTELAMENTO D...,MACEIÓ
1,16386,01/07/2022,MARIA CLARA ROSENO DA SILVA (113523) ...,103.254.424-44,220.74,TRANSGUARD DO BRASIL REMOCAO E ACAUTELAMENTO D...,MACEIÓ
2,16387,01/07/2022,SANDRA GOMES DE ANDRADE PROTASIO (113530) ...,700.565.604-00,71.30,TRANSGUARD DO BRASIL REMOCAO E ACAUTELAMENTO D...,MACEIÓ
3,16388,01/07/2022,SANDRA GOMES DE ANDRADE PROTASIO (113530) ...,700.565.604-00,220.74,TRANSGUARD DO BRASIL REMOCAO E ACAUTELAMENTO D...,MACEIÓ
4,16391,04/07/2022,JOSE IBIS TORRES (114087) ...,057.589.384-24,34.08,TRANSGUARD DO BRASIL REMOCAO E ACAUTELAMENTO D...,MACEIÓ
...,...,...,...,...,...,...,...
3222,168,26/07/2022,CLAUDIO LUIS SILVA MACHADO (117546) ...,927.289.956-72,262.23,TRANSGUARD DO BRASIL REMOCAO E ACAUTELAMENTO D...,TG TRÊS RIOS
3223,169,27/07/2022,RAMON DE OLIVEIRA GONCALEZ (117561) ...,128.880.987-50,173.33,TRANSGUARD DO BRASIL REMOCAO E ACAUTELAMENTO D...,TG TRÊS RIOS
3224,170,27/07/2022,RAMON DE OLIVEIRA GONCALEZ (117561) ...,128.880.987-50,108.54,TRANSGUARD DO BRASIL REMOCAO E ACAUTELAMENTO D...,TG TRÊS RIOS
3225,171,28/07/2022,MARLON RAMOS DE AQUINO (117603) ...,185.198.127-67,179.48,TRANSGUARD DO BRASIL REMOCAO E ACAUTELAMENTO D...,TG TRÊS RIOS
3226,172,28/07/2022,MARLON RAMOS DE AQUINO (117603) ...,185.198.127-67,325.62,TRANSGUARD DO BRASIL REMOCAO E ACAUTELAMENTO D...,TG TRÊS RIOS

701644.1099999999

Nota                  int64
Data                 object
Tomador              object
CNPJ_CPF_Tomador     object
Valor               float64
Empresa              object
Unidade              object
dtype: object

In [125]:
# Barra do Piraí

arquivo = pd.read_excel(r'C:\Users\L_SAR\Documents\Desenv\notas\barra_do_pirai\Barra_do_Pirai_Transguard.xlsx')

# Selecionando as colunas que serão utilizadas:
barra_pirai = arquivo[['Número', 'Emissão', 'Razão Social', 'Tomador', 'Serviço(R$)', 'Incidência']]

# Renomeando campo para que ele não seja renomeado duas vezes:
barra_pirai = barra_pirai.rename(columns = {'Tomador' : 'Tomador_temp'})

# Apagando linhas em branco ou linhas de totais:
barra_pirai = barra_pirai.dropna(subset = ['Número'])


# Renomeando os campos para o padrão:
barra_pirai = barra_pirai.rename(columns = {'Número' : 'Nota'})
barra_pirai = barra_pirai.rename(columns = {'Emissão' : 'Data'})
barra_pirai = barra_pirai.rename(columns = {'Razão Social' : 'Tomador'})
barra_pirai = barra_pirai.rename(columns = {'Tomador_temp' : 'CNPJ_CPF_Tomador'})
barra_pirai = barra_pirai.rename(columns = {'Serviço(R$)' : 'Valor'})
barra_pirai = barra_pirai.rename(columns = {'Incidência' : 'Unidade'})

# Criando coluna que falta:
barra_pirai['Empresa'] = 'Microsoft Corp Inc'

# Reordenando os campos:
barra_pirai = barra_pirai[['Nota', 'Data', 'Tomador', 'CNPJ_CPF_Tomador', 'Valor', 'Empresa','Unidade']]

# Convertendo tipos de campos:
barra_pirai['Data'] = barra_pirai['Data'].astype(str)


# Valor total para verificar integridade do dataframe:
faturamento_barra_pirai = barra_pirai['Valor'].sum()

#display(barra_pirai)

print(faturamento_barra_pirai)

barra_pirai.dtypes

27246.61

Nota                  int64
Data                 object
Tomador              object
CNPJ_CPF_Tomador     object
Valor               float64
Empresa              object
Unidade              object
dtype: object

In [126]:
# Caicó Transguard

arquivo = pd.read_excel(r'C:\Users\L_SAR\Documents\Desenv\notas\caico\caico.xlsx')

# Selecionando as colunas que serão utilizadas:
caico = arquivo[['Número', 'Data', 'Tomador de Serviços', 'CPF/CNPJ', 'Valor Serviços R$']]

# Renomeando campo para que ele não seja renomeado duas vezes:
caico = caico.rename(columns = {'Data' : 'Data_caico'})

# Apagando linhas em branco ou linhas de totais:
caico = caico.dropna(subset = ['Número'])

# Renomeando os campos para o padrão:
caico = caico.rename(columns = {'Número' : 'Nota'})
caico = caico.rename(columns = {'Data_caico' : 'Data'})
caico = caico.rename(columns = {'Tomador de Serviços' : 'Tomador'})
caico = caico.rename(columns = {'CPF/CNPJ' : 'CNPJ_CPF_Tomador'})
caico = caico.rename(columns = {'Valor Serviços R$' : 'Valor'})

# Criando coluna que falta:
caico['Empresa'] = 'Microsoft Corp Inc'
caico['Unidade'] = 'Caico'

# Reordenando os campos:
caico = caico[['Nota', 'Data', 'Tomador', 'CNPJ_CPF_Tomador', 'Valor', 'Empresa', 'Unidade']]

# Convertendo tipos de campos:
caico["Nota"] = caico["Nota"].apply(np.int64)
caico['Data'] = caico['Data'].astype(str)


# Valor total para verificar integridade do dataframe:
faturamento_caico = caico['Valor'].sum()

#display(caico)

print(faturamento_caico)

caico.dtypes

7229.720000000001

Nota                  int64
Data                 object
Tomador              object
CNPJ_CPF_Tomador     object
Valor               float64
Empresa              object
Unidade              object
dtype: object

In [127]:
# Caruaru Transguard, Pernambuco

arquivo = pd.read_excel(r'C:\Users\L_SAR\Documents\Desenv\notas\caruaru\Caruaru_Transguard.xlsx')

# Selecionando as colunas que serão utilizadas:
caruaru = arquivo[['ns2:Numero', 'ns2:DataEmissao', 'ns2:RazaoSocial5', 'ns2:Cpf', 'ns2:ValorServicos', 'ns2:Endereco6', 'ns2:NomeFantasia']]

# Apagando linhas em branco ou linhas de totais:
caruaru = caruaru.dropna(subset = ['ns2:Numero'])

# Renomeando os campos para o padrão:
caruaru = caruaru.rename(columns = {'ns2:Numero' : 'Nota'})
caruaru = caruaru.rename(columns = {'ns2:DataEmissao' : 'Data'})
caruaru = caruaru.rename(columns = {'ns2:RazaoSocial5' : 'Tomador'})
caruaru = caruaru.rename(columns = {'ns2:Cpf' : 'CNPJ_CPF_Tomador'})
caruaru = caruaru.rename(columns = {'ns2:ValorServicos' : 'Valor'})
caruaru = caruaru.rename(columns = {'ns2:Endereco6' : 'Empresa'})
caruaru = caruaru.rename(columns = {'ns2:NomeFantasia' : 'Unidade'})


# Convertendo tipos de campos:
caruaru["Nota"] = caruaru["Nota"].apply(np.int64)
caruaru['CNPJ_CPF_Tomador'] = caruaru['CNPJ_CPF_Tomador'].astype(str)
caruaru['Data'] = caruaru['Data'].astype(str)

# Valor total para verificar integridade do dataframe:
faturamento_caruaru = caruaru['Valor'].sum()

#display(caruaru)

print(faturamento_caruaru)

caruaru.dtypes

35761.079999999994

Nota                  int64
Data                 object
Tomador              object
CNPJ_CPF_Tomador     object
Valor               float64
Empresa              object
Unidade              object
dtype: object

In [128]:
# Ceilandia Transguard

arquivo = pd.read_excel(r'C:\Users\L_SAR\Documents\Desenv\notas\ceilandia\Ceilandia_Transguard.xlsx')

# Selecionando as colunas que serão utilizadas:
ceilandia = arquivo[['Número', 'Data de emissão', 'Destinatário', 'Doc. Destinatário', 'Valor']]

# Renomeando campo para que ele não seja renomeado duas vezes:
ceilandia = ceilandia.rename(columns = {'Valor' : 'Valor_Total'})
ceilandia = ceilandia.rename(columns = {'Empresa' : 'Empresa_Nome'})

# Apagando linhas em branco ou linhas de totais:
ceilandia = ceilandia.dropna(subset = ['Número'])

# Renomeando os campos para o padrão:
ceilandia = ceilandia.rename(columns = {'Número' : 'Nota'})
ceilandia = ceilandia.rename(columns = {'Data de emissão' : 'Data'})
ceilandia = ceilandia.rename(columns = {'Destinatário' : 'Tomador'})
ceilandia = ceilandia.rename(columns = {'Doc. Destinatário' : 'CNPJ_CPF_Tomador'})
ceilandia = ceilandia.rename(columns = {'Valor_Total' : 'Valor'})
ceilandia = ceilandia.rename(columns = {'Empresa_Nome' : 'Empresa'})

# Criando coluna que falta:
ceilandia['Empresa'] = 'Microsoft Corp Inc'
ceilandia['Unidade'] = 'Ceilandia'

# Reordenando os campos:
ceilandia = ceilandia[['Nota', 'Data', 'Tomador', 'CNPJ_CPF_Tomador', 'Valor', 'Empresa', 'Unidade']]

# Convertendo tipos de campos:
ceilandia['Nota'] = ceilandia['Nota'].apply(np.int64)

# Valor total para verificar integridade do dataframe:
faturamento_ceilandia = ceilandia['Valor'].sum()

#display(base_sistema)

print(faturamento_ceilandia)

ceilandia.dtypes

156902.43

Nota                  int64
Data                 object
Tomador              object
CNPJ_CPF_Tomador     object
Valor               float64
Empresa              object
Unidade              object
dtype: object

In [129]:
# Coite SPE

arquivo = pd.read_excel(r'C:\Users\L_SAR\Documents\Desenv\notas\coite\coite.xlsx')

# Selecionando as colunas que serão utilizadas:
coite = arquivo[['Nota', 'Emissão', 'Tomador', 'CNPJ/CPF Tomador', 'Valor Total']]

# Renomeando campo para que ele não seja renomeado duas vezes:
coite = coite.rename(columns = {'Nota' : 'Nota_coite'})
coite = coite.rename(columns = {'Tomador' : 'Tomador_coite'})

# Renomeando os campos para o padrão:
coite = coite.rename(columns = {'Nota_coite' : 'Nota'})
coite = coite.rename(columns = {'Emissão' : 'Data'})
coite = coite.rename(columns = {'Tomador_coite' : 'Tomador'})
coite = coite.rename(columns = {'CNPJ/CPF Tomador' : 'CNPJ_CPF_Tomador'})
coite = coite.rename(columns = {'Valor Total' : 'Valor'})

# Apagando linhas em branco ou linhas de totais:
coite = coite.dropna(subset = ['Nota'])

# Criando coluna que falta:
coite['Empresa'] = 'Microsoft Corp Inc'
coite['Unidade'] = 'Coite'

# Reordenando os campos:
coite = coite[['Nota', 'Data', 'Tomador', 'CNPJ_CPF_Tomador', 'Valor', 'Empresa', 'Unidade']]

# Convertendo tipos de campos:
coite['Data'] = coite['Data'].astype(str)

# Valor total para verificar integridade do dataframe:
faturamento_coite = coite['Valor'].sum()

#display(coite)

print(faturamento_coite)

coite.dtypes

7489.469999999999

Nota                  int64
Data                 object
Tomador              object
CNPJ_CPF_Tomador     object
Valor               float64
Empresa              object
Unidade              object
dtype: object

In [130]:
# Cuiaba Nova

arquivo = pd.read_excel(r'C:\Users\L_SAR\Documents\Desenv\notas\cuiaba\cuiaba.xlsx')

# Selecionando as colunas que serão utilizadas:
cuiaba = arquivo[['Nº Doc.', 'Dt.Emissão', 'CPF/CNPJ Tomador', 'Valor Doc. (R$)']]

# Apagando linhas em branco ou linhas de totais:
cuiaba = cuiaba.dropna(subset = ['Nº Doc.'])


# Renomeando os campos para o padrão:
cuiaba = cuiaba.rename(columns = {'Nº Doc.' : 'Nota'})
cuiaba = cuiaba.rename(columns = {'Dt.Emissão' : 'Data'})
cuiaba = cuiaba.rename(columns = {'CPF/CNPJ Tomador' : 'CNPJ_CPF_Tomador'})
cuiaba = cuiaba.rename(columns = {'Valor Doc. (R$)' : 'Valor'})

# Criando coluna que falta:
cuiaba['Tomador'] = ''
cuiaba['Empresa'] = 'Microsoft Corp Inc'
cuiaba['Unidade'] = 'Cuiaba'

# Reordenando os campos:
cuiaba = cuiaba[['Nota', 'Data', 'Tomador', 'CNPJ_CPF_Tomador', 'Valor', 'Empresa','Unidade']]

# Convertendo tipos de campos:
cuiaba['Data'] = cuiaba['Data'].astype(str)


# Valor total para verificar integridade do dataframe:
faturamento_cuiaba = cuiaba['Valor'].sum()

#display(cuiaba)

print(faturamento_cuiaba)

cuiaba.dtypes

371192.5

Nota                  int64
Data                 object
Tomador              object
CNPJ_CPF_Tomador     object
Valor               float64
Empresa              object
Unidade              object
dtype: object

In [131]:
# Itabuna Transguard Nordeste

arquivo = pd.read_excel(r'C:\Users\L_SAR\Documents\Desenv\notas\itabuna\Itabuna_Transguard_Nordeste.xlsx')

# Selecionando as colunas que serão utilizadas:
itabuna = arquivo[['Número', 'Emissão', 'Razão Social', 'Tomador', 'Total(R$)', 'Incidência']]

# Renomeando campo para que ele não seja renomeado duas vezes:
itabuna = itabuna.rename(columns = {'Tomador' : 'Tomador_itabuna'})

# Apagando linhas em branco ou linhas de totais:
itabuna = itabuna.dropna(subset = ['Número'])

# Renomeando os campos para o padrão:
itabuna = itabuna.rename(columns = {'Número' : 'Nota'})
itabuna = itabuna.rename(columns = {'Emissão' : 'Data'})
itabuna = itabuna.rename(columns = {'Razão Social' : 'Tomador'})
itabuna = itabuna.rename(columns = {'Tomador_itabuna' : 'CNPJ_CPF_Tomador'})
itabuna = itabuna.rename(columns = {'Total(R$)' : 'Valor'})
itabuna = itabuna.rename(columns = {'Incidência' : 'Unidade'})

# Criando coluna que falta:
itabuna['Empresa'] = 'Microsoft Corp Inc'

# Reordenando os campos:
itabuna = itabuna[['Nota', 'Data', 'Tomador', 'CNPJ_CPF_Tomador', 'Valor', 'Empresa','Unidade']]

# Convertendo tipos de campos:
itabuna['Nota'] = itabuna['Nota'].apply(np.int64)
itabuna['Data'] = itabuna['Data'].astype(str)


# Valor total para verificar integridade do dataframe:
faturamento_itabuna = itabuna['Valor'].sum()

#display(itabuna)

print(faturamento_itabuna)

itabuna.dtypes

9629.0

Nota                  int64
Data                 object
Tomador              object
CNPJ_CPF_Tomador     object
Valor               float64
Empresa              object
Unidade              object
dtype: object

In [132]:
# Itaguai Transguard

arquivo = pd.read_excel(r"C:\Users\L_SAR\Documents\Desenv\notas\itaguai\itaguai_Tranguard.xlsx") # 

# Selecionando as colunas que serão utilizadas:
itaguai_trans = arquivo[["ns1:Numero", "ns1:DataEmissaoRps", "ns1:RazaoSocial4", "ns1:Cnpj", "ns1:ValorServicos", "ns1:RazaoSocial"]]

# Apagando linhas em branco:
itaguai_trans = itaguai_trans.dropna(subset=['ns1:Numero'])

# Criando campos adicionais:
itaguai_trans["Unidade"] = "Itaguai_Transguard"

# Renomeando os campos para o padrão:
itaguai_trans = itaguai_trans.rename(columns={"ns1:Numero": "Nota"})
itaguai_trans = itaguai_trans.rename(columns={"ns1:DataEmissaoRps": "Data"})
itaguai_trans = itaguai_trans.rename(columns={"ns1:RazaoSocial4": "Tomador"})
itaguai_trans = itaguai_trans.rename(columns={"ns1:Cnpj": "CNPJ_CPF_Tomador"})
itaguai_trans = itaguai_trans.rename(columns={"ns1:ValorServicos": "Valor"})
itaguai_trans = itaguai_trans.rename(columns={"ns1:RazaoSocial": "Empresa"})

# Reordenando colunas:
itaguai_trans = itaguai_trans[['Nota','Data','Tomador','CNPJ_CPF_Tomador','Valor', 'Empresa', 'Unidade']]

# Convertendo tipos de campos:
itaguai_trans["Nota"] = itaguai_trans["Nota"].apply(np.int64) # Converte INT64
itaguai_trans["Data"] = itaguai_trans["Data"].astype(str)
itaguai_trans["CNPJ_CPF_Tomador"] = itaguai_trans["CNPJ_CPF_Tomador"].astype(str)


# Valor total:
faturamento_itaguai_trans = itaguai_trans["Valor"].sum()

#display(itaguai_trans)

print ("Total:", faturamento_itaguai_trans)

itaguai_trans.dtypes

Total: 28776.54

Nota                  int64
Data                 object
Tomador              object
CNPJ_CPF_Tomador     object
Valor               float64
Empresa              object
Unidade              object
dtype: object

In [133]:
# Itaperuna Nova Rl

arquivo = pd.read_excel(r"C:\Users\L_SAR\Documents\Desenv\notas\itaperuna\ITAPERUNA.xlsx") # 

# Selecionando as colunas que serão utilizadas:
itaperuna_nova_rl = arquivo[["Numero", "DataEmissao", "RazaoSocial13", "Cpf", "ValorServicos", "RazaoSocial"]]

# Apagando linhas em branco:
itaperuna_nova_rl = itaperuna_nova_rl.dropna(subset=['Numero'])

# Criando campos adicionais:
itaperuna_nova_rl["Unidade"] = "Itaperuna Nova RL"

# Renomeando os campos para o padrão:
itaperuna_nova_rl = itaperuna_nova_rl.rename(columns={"Numero": "Nota"})
itaperuna_nova_rl = itaperuna_nova_rl.rename(columns={"DataEmissao": "Data"})
itaperuna_nova_rl = itaperuna_nova_rl.rename(columns={"RazaoSocial13": "Tomador"})
itaperuna_nova_rl = itaperuna_nova_rl.rename(columns={"Cpf": "CNPJ_CPF_Tomador"})
itaperuna_nova_rl = itaperuna_nova_rl.rename(columns={"ValorServicos": "Valor"})
itaperuna_nova_rl = itaperuna_nova_rl.rename(columns={"RazaoSocial": "Empresa"})

# Reordenando colunas:
itaperuna_nova_rl = itaperuna_nova_rl[['Nota','Data','Tomador','CNPJ_CPF_Tomador','Valor', 'Empresa', 'Unidade']]

# Convertendo tipos de campos:
itaperuna_nova_rl["Data"] = itaperuna_nova_rl["Data"].astype(str)
itaperuna_nova_rl["CNPJ_CPF_Tomador"] = itaperuna_nova_rl["CNPJ_CPF_Tomador"].astype(str)

# Valor total:
faturamento_itaperuna_nova_rl = itaperuna_nova_rl["Valor"].sum()

#display(itaperuna_nova_rl)

print ("Total:", faturamento_itaperuna_nova_rl)

itaperuna_nova_rl.dtypes

Total: 4247.96

Nota                  int64
Data                 object
Tomador              object
CNPJ_CPF_Tomador     object
Valor               float64
Empresa              object
Unidade              object
dtype: object

In [134]:
# Maceió Transguard

arquivo = pd.read_excel(r"C:\Users\L_SAR\Documents\Desenv\notas\maceio\Maceio_Transguard.xlsx") # 

# Selecionando as colunas que serão utilizadas:
maceio_trans = arquivo[["NUMERO DOCUMENTO", "DATA EMISSAO", "RAZAO SOCIAL TOMADOR", "CNPJ/CPF TOMADOR", "VALOR DO SERVICO", "RAZAO SOCIAL PRESTADOR", "LOCAL DA PRESTAÇÃO"]]

# Apagando linhas em branco:
maceio_trans = maceio_trans.dropna(subset=['NUMERO DOCUMENTO'])

# Renomeando os campos para o padrão:
maceio_trans = maceio_trans.rename(columns={"NUMERO DOCUMENTO": "Nota"})
maceio_trans = maceio_trans.rename(columns={"DATA EMISSAO": "Data"})
maceio_trans = maceio_trans.rename(columns={"RAZAO SOCIAL TOMADOR": "Tomador"})
maceio_trans = maceio_trans.rename(columns={"CNPJ/CPF TOMADOR": "CNPJ_CPF_Tomador"})
maceio_trans = maceio_trans.rename(columns={"VALOR DO SERVICO": "Valor"})
maceio_trans = maceio_trans.rename(columns={"RAZAO SOCIAL PRESTADOR": "Empresa"})
maceio_trans = maceio_trans.rename(columns={"LOCAL DA PRESTAÇÃO": "Unidade"})

# Convertendo tipos de campos:
maceio_trans["Nota"] = maceio_trans["Nota"].apply(np.int64) # Converte INT64
maceio_trans["CNPJ_CPF_Tomador"] = maceio_trans["CNPJ_CPF_Tomador"].astype(str)

# Valor total:
faturamento_maceio_trans = maceio_trans["Valor"].sum()

#display(maceio_trans)

print ("Total:", faturamento_maceio_trans)

maceio_trans.dtypes

Total: 67462.33

Nota                  int64
Data                 object
Tomador              object
CNPJ_CPF_Tomador     object
Valor               float64
Empresa              object
Unidade              object
dtype: object

In [135]:
# Magé - Nova RL

arquivo = pd.read_excel(r"C:\Users\L_SAR\Documents\Desenv\notas\mage_nova_rl\Mage_Nova_RL.xls")

#--------------------------------------------RESOLVENDO PROBLEMA DO CAMPO TOMADOR (JUNTO COM CPF)--------------------------------------------------
# Apagando linhas em branco para poder trabalhar o campo:
arquivo = arquivo.dropna(subset=['N° da Nota'])

# Fazer slice do campo 'Tomador' para compor o campo CPF:
tomador_temp = arquivo['Tomador'].str.slice(start = 16)
cpf_temp = arquivo['Tomador'].str.slice(start = 1, stop = 12)

# Criando campos para separar os dados:
arquivo['tomador_temp'] = (tomador_temp)
arquivo['cpf_temp'] = (cpf_temp)

#display(arquivo)
#--------------------------------------------------------------------------------------------------------------------------------------------------

# Selecionando as colunas que serão utilizadas:
mage_nova_rl = arquivo[["N° da Nota", "Data Emissão", "tomador_temp", "cpf_temp", "Valor do Serviço", "Local Incidência"]]

# Apagando linhas em branco:
mage_nova_rl = mage_nova_rl.dropna(subset=['N° da Nota'])

# Criando campos adicionais:
mage_nova_rl["Empresa"] = 'Nova RL'

# Renomeando os campos para o padrão:
mage_nova_rl = mage_nova_rl.rename(columns={"N° da Nota": "Nota"})
mage_nova_rl = mage_nova_rl.rename(columns={"Data Emissão": "Data"})
mage_nova_rl = mage_nova_rl.rename(columns={"tomador_temp": "Tomador"})
mage_nova_rl = mage_nova_rl.rename(columns={"cpf_temp": "CNPJ_CPF_Tomador"})
mage_nova_rl = mage_nova_rl.rename(columns={"Valor do Serviço": "Valor"})
mage_nova_rl = mage_nova_rl.rename(columns={"Local Incidência": "Unidade"})

# Reordenando colunas:
mage_nova_rl = mage_nova_rl[['Nota','Data','Tomador','CNPJ_CPF_Tomador','Valor', 'Empresa', 'Unidade']]

# Convertendo tipos de campos:
mage_nova_rl["Data"] = mage_nova_rl["Data"].astype(str)

# Valor total:
faturamento_mage_nova_rl = mage_nova_rl["Valor"].sum()

#display(mage_nova_rl)

print ("Total:", faturamento_mage_nova_rl)

mage_nova_rl.dtypes

Total: 14821.02

Nota                  int64
Data                 object
Tomador              object
CNPJ_CPF_Tomador     object
Valor               float64
Empresa              object
Unidade              object
dtype: object

In [136]:
# Magé Transguard

arquivo = pd.read_excel(r"C:\Users\L_SAR\Documents\Desenv\notas\mage_transguard\Mage_Transguard.xlsx") # 

#--------------------------------------------RESOLVENDO PROBLEMA DO CAMPO TOMADOR (JUNTO COM CPF)--------------------------------------------------
# Apagando linhas em branco para poder trabalhar o campo:
arquivo = arquivo.dropna(subset=['N° da Nota'])

# Fazer slice do campo 'Tomador' para compor o campo CPF:
tomador_temp = arquivo['Tomador'].str.slice(start = 16)
cpf_temp = arquivo['Tomador'].str.slice(start = 1, stop = 12)

# Criando campos para separar os dados:
arquivo['tomador_temp'] = (tomador_temp)
arquivo['cpf_temp'] = (cpf_temp)

#display(arquivo)
#--------------------------------------------------------------------------------------------------------------------------------------------------

# Selecionando as colunas que serão utilizadas:
mage_transguard = arquivo[["N° da Nota", "Data Emissão", "tomador_temp", "cpf_temp", "Valor do Serviço", "Local Incidência"]]

# Apagando linhas em branco:
mage_transguard = mage_transguard.dropna(subset=['N° da Nota'])

# Criando campos adicionais:
mage_transguard["Empresa"] = "Transguard"

# Renomeando os campos para o padrão:
mage_transguard = mage_transguard.rename(columns={"N° da Nota": "Nota"})
mage_transguard = mage_transguard.rename(columns={"Data Emissão": "Data"})
mage_transguard = mage_transguard.rename(columns={"tomador_temp": "Tomador"})
mage_transguard = mage_transguard.rename(columns={"cpf_temp": "CNPJ_CPF_Tomador"})
mage_transguard = mage_transguard.rename(columns={"Valor do Serviço": "Valor"})
mage_transguard = mage_transguard.rename(columns={"Local Incidência": "Unidade"})

# Reordenando colunas:
mage_transguard = mage_transguard[['Nota','Data','Tomador','CNPJ_CPF_Tomador','Valor', 'Empresa', 'Unidade']]

# Convertendo tipos de campos:
mage_transguard["Data"] = mage_transguard["Data"].astype(str)

# Valor total:
faturamento_mage_transguard = mage_transguard["Valor"].sum()

#display(mage_transguard)

print ("Total:", faturamento_mage_transguard)

mage_transguard.dtypes

Total: 17552.36

Nota                  int64
Data                 object
Tomador              object
CNPJ_CPF_Tomador     object
Valor               float64
Empresa              object
Unidade              object
dtype: object

In [137]:
# Mossoró Transguard

arquivo = pd.read_excel(r"C:\Users\L_SAR\Documents\Desenv\notas\mossoro_transguard\Mossoro_Transguard_DUPLICADOS.xlsx")

#--------------------------------------------Ajustando Duplicidade--------------------------------------------------
# Renomeando o campo antes de selecionar:
#arquivo = arquivo.rename(columns = {'ValorServicos' : 'Valor'})

# Apagando as linhas duplicadas:
#arquivo = arquivo.sort_values('RazaoSocial3', ascending = False)
arquivo = arquivo.drop_duplicates(subset = 'ns1:Numero', keep = 'first')

#-------------------------------------------------------------------------------------------------------------------
# Selecionando as colunas que serão utilizadas:
mossoro_trans = arquivo[["ns1:Numero","ns1:DataEmissaoRps", "RazaoSocial3", "Cpf", "ValorServicos", "RazaoSocial"]]

# Apagando linhas em branco:
mossoro_trans = mossoro_trans.dropna(subset=['ns1:Numero'])

# Criando campos adicionais:
mossoro_trans["Unidade"] = "Mossoro"

# Renomeando os campos para o padrão:
mossoro_trans = mossoro_trans.rename(columns={"ns1:Numero": "Nota"})
mossoro_trans = mossoro_trans.rename(columns={"ns1:DataEmissaoRps": "Data"})
mossoro_trans = mossoro_trans.rename(columns={"RazaoSocial3": "Tomador"})
mossoro_trans = mossoro_trans.rename(columns={"Cpf": "CNPJ_CPF_Tomador"})
mossoro_trans = mossoro_trans.rename(columns={"ValorServicos": "Valor"})
mossoro_trans = mossoro_trans.rename(columns={"RazaoSocial": "Empresa"})

# Reordenando colunas:
mossoro_trans = mossoro_trans[['Nota','Data','Tomador','CNPJ_CPF_Tomador','Valor', 'Empresa', 'Unidade']]

# Convertendo tipos de campos:
mossoro_trans["Nota"] = mossoro_trans["Nota"].apply(np.int64) # Converte INT64
mossoro_trans["Data"] = mossoro_trans["Data"].astype(str)
mossoro_trans["CNPJ_CPF_Tomador"] = mossoro_trans["CNPJ_CPF_Tomador"].astype(str)

# Valor total:
faturamento_mossoro_trans = mossoro_trans["Valor"].sum()

#display(mossoro_trans)

print ("Total:", faturamento_mossoro_trans)

mossoro_trans.dtypes

Total: 24716.72

Nota                  int64
Data                 object
Tomador              object
CNPJ_CPF_Tomador     object
Valor               float64
Empresa              object
Unidade              object
dtype: object

In [138]:
# Natal - Transguard

arquivo = pd.read_excel(r"C:\Users\L_SAR\Documents\Desenv\notas\natal_transguard\Natal - Transguard.xlsx")  

# Transformando a primeira linha em cabeçalho:
arquivo.columns = arquivo.iloc[0]

# Selecionando as colunas que serão utilizadas:
natal_trans = arquivo[["N° Nota", "Emissão", "Tomador", "Serviço(R$)", "Prestador"]]

# Apagando linhas em branco:
natal_trans = natal_trans.dropna(subset=['N° Nota'])

# Criando campos adicionais:
natal_trans["Unidade"] = "Natal - Transguard"
natal_trans["CNPJ_CPF_Tomador"] = ""
    
# Renomeando os campos para o padrão:
natal_trans = natal_trans.rename(columns={"N° Nota": "Nota"})
natal_trans = natal_trans.rename(columns={"Emissão": "Data"})
natal_trans = natal_trans.rename(columns={"Tomador": "Tomador"})
natal_trans = natal_trans.rename(columns={"Serviço(R$)": "Valor"})
natal_trans = natal_trans.rename(columns={"Prestador": "Empresa"})

# Reordenando colunas:
natal_trans = natal_trans[['Nota','Data','Tomador','CNPJ_CPF_Tomador','Valor', 'Empresa', 'Unidade']]

#--------------------------------------------Resolvendo cabeçalho repetido--------------------------------------------------

# Pegando os nomes das colunas para indexar:
index_nomes = natal_trans[natal_trans["Nota"] == "N° Nota"].index

# Apagando a linha idexada:
natal_trans.drop(index_nomes, inplace = True)

#-------------------------------------------------------------------------------------------------------------------

# Convertendo tipos de campos:
natal_trans["Nota"] = natal_trans["Nota"].apply(np.int64) # Converte INT64
natal_trans["Valor"] = natal_trans["Valor"].astype(float)

# Valor total:
faturamento_natal_trans = natal_trans["Valor"].sum()

#display(natal_trans)

print ("Total:", faturamento_natal_trans)

natal_trans.dtypes

Total: 33943.740000000005

0
Nota                  int64
Data                 object
Tomador              object
CNPJ_CPF_Tomador     object
Valor               float64
Empresa              object
Unidade              object
dtype: object

In [139]:
# Petrolina RL

arquivo = pd.read_excel(r"C:\Users\L_SAR\Documents\Desenv\notas\petrolina_rl\Petrolina_RL.xlsx")  

#----------------------------------------------------SEPARAR CPF E TOMADOR----------------------------------------------------

# Apagando linhas em branco:
arquivo = arquivo.dropna(subset = "Número")

# Fazendo slice do campo tomador para compor o campo CPF:
tomador_temp = arquivo["Tomador"].str.slice(start = 17)
cpf_temp = arquivo["Tomador"].str.slice(start = 0, stop = 14)

# Criando campos para separar os dados:
arquivo["Tomador"] = (tomador_temp)
arquivo["CNPJ_CPF_Tomador"] = (cpf_temp)

#-----------------------------------------------------------------------------------------------------------------------------

# Selecionando as colunas que serão utilizadas:
petrolina_rl = arquivo[["Número", "Emissão", "Tomador", "CNPJ_CPF_Tomador", "Valor"]]

# Criando campos adicionais:
petrolina_rl["Empresa"] = "Petrolina RL"
petrolina_rl["Unidade"] = "Petrolina RL"

# Renomeando os campos para o padrão:
petrolina_rl = petrolina_rl.rename(columns={"Número": "Nota"})
petrolina_rl = petrolina_rl.rename(columns={"Emissão": "Data"})
#petrolina_rl = petrolina_rl.rename(columns={"": "Tomador"})
#petrolina_rl = petrolina_rl.rename(columns={"": "CNPJ_CPF_Tomador"})
petrolina_rl = petrolina_rl.rename(columns={"Valor": "Valor"})

# Reordenando colunas:
petrolina_rl = petrolina_rl[['Nota','Data',"Tomador", "CNPJ_CPF_Tomador",'Valor', 'Empresa', 'Unidade']]

# Convertendo tipos de campos:
#petrolina_rl[""] = petrolina_rl[""].apply(np.int64) # Converte INT64
petrolina_rl["Data"] = petrolina_rl["Data"].astype(str)

# Valor total:
faturamento_petrolina_rl = petrolina_rl["Valor"].sum()

#display(petrolina_rl)

print ("Total:", faturamento_petrolina_rl)

petrolina_rl.dtypes

Total: 1635.83

C:\Users\L_SAR\AppData\Local\Temp\ipykernel_13500\3032514744.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  petrolina_rl["Empresa"] = "Petrolina RL"
C:\Users\L_SAR\AppData\Local\Temp\ipykernel_13500\3032514744.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  petrolina_rl["Unidade"] = "Petrolina RL"

Nota                  int64
Data                 object
Tomador              object
CNPJ_CPF_Tomador     object
Valor               float64
Empresa              object
Unidade              object
dtype: object

In [140]:
# Salgueiro - Transguard

arquivo = pd.read_excel(r"C:\Users\L_SAR\Documents\Desenv\notas\salgueiro\Salgueiro_Transguard.xls") # 

# Selecionando as colunas que serão utilizadas:
salgueiro_trans = arquivo[["Numero", "Data", "Nome tomador", "Doc tomador", "Valor", "Razao social prestador", "Cidade"]]

# Apagando linhas em branco:
salgueiro_trans = salgueiro_trans.dropna(subset=['Numero'])

# Renomeando os campos para o padrão:
salgueiro_trans = salgueiro_trans.rename(columns={"Numero": "Nota"})
salgueiro_trans = salgueiro_trans.rename(columns={"Data": "Data"})
salgueiro_trans = salgueiro_trans.rename(columns={"Nome tomador": "Tomador"})
salgueiro_trans = salgueiro_trans.rename(columns={"Doc tomador": "CNPJ_CPF_Tomador"})
salgueiro_trans = salgueiro_trans.rename(columns={"Valor": "Valor"})
salgueiro_trans = salgueiro_trans.rename(columns={"Razao social prestador": "Empresa"})
salgueiro_trans = salgueiro_trans.rename(columns={"Cidade": "Unidade"})

# Convertendo tipos de campos:
salgueiro_trans["Nota"] = salgueiro_trans["Nota"].apply(np.int64) # Converte INT64
salgueiro_trans["CNPJ_CPF_Tomador"] = salgueiro_trans["CNPJ_CPF_Tomador"].astype(str)

# Valor total:
faturamento_salgueiro_trans = salgueiro_trans["Valor"].sum()

#display(salgueiro_trans)

print ("Total:", faturamento_salgueiro_trans)

salgueiro_trans.dtypes

Total: 41247.240000000005

Nota                  int64
Data                 object
Tomador              object
CNPJ_CPF_Tomador     object
Valor               float64
Empresa              object
Unidade              object
dtype: object

In [141]:
# São Caetano - Nova RL

arquivo = pd.read_excel(r"C:\Users\L_SAR\Documents\Desenv\notas\sao_caetano_nova_rl\Sao_Caetano - Nova RL.xlsx")  

# Selecionando as colunas que serão utilizadas:
sao_caetano_nova_rl = arquivo[["NF INI", "DIA", "NOME DA RAZÃO SOCIAL", "CNPJ/CPF", "VAL. FATURADO"]]

# Apagando linhas em branco:
sao_caetano_nova_rl = sao_caetano_nova_rl.dropna(subset=['NF INI'])

# Criando campos adicionais:
sao_caetano_nova_rl["Empresa"] = "São Caetano - Nova RL"
sao_caetano_nova_rl["Unidade"] = "São Caetano - Nova RL"

# Renomeando os campos para o padrão:
sao_caetano_nova_rl = sao_caetano_nova_rl.rename(columns={"NF INI": "Nota"})
sao_caetano_nova_rl = sao_caetano_nova_rl.rename(columns={"DIA": "DIA_temp"})
sao_caetano_nova_rl = sao_caetano_nova_rl.rename(columns={"NOME DA RAZÃO SOCIAL": "Tomador"})
sao_caetano_nova_rl = sao_caetano_nova_rl.rename(columns={"CNPJ/CPF": "CNPJ_CPF_Tomador"})
sao_caetano_nova_rl = sao_caetano_nova_rl.rename(columns={"VAL. FATURADO": "Valor"})

#-------------------------------------------------Resolvendo problema campo Data----------------------------------------------
# Convertendo tipos de campos:
sao_caetano_nova_rl["DIA_temp"] = sao_caetano_nova_rl["DIA_temp"].astype(str)

# Criando variável mes e ano:
sao_caetano_nova_rl['Mes_ano'] = '/07/2022'

# Concatenando a coluna DIA com a coluna Mes_ano:
sao_caetano_nova_rl['Data'] = sao_caetano_nova_rl['DIA_temp'] + sao_caetano_nova_rl['Mes_ano']

#-----------------------------------------------------------------------------------------------------------------------------

# Reordenando colunas:
sao_caetano_nova_rl = sao_caetano_nova_rl[['Nota', 'Data', 'Tomador','CNPJ_CPF_Tomador','Valor', 'Empresa', 'Unidade']]

# Valor total:
faturamento_sao_caetano_nova_rl = sao_caetano_nova_rl["Valor"].sum()

#display(sao_caetano_nova_rl)

print ("Total:", faturamento_sao_caetano_nova_rl)

sao_caetano_nova_rl.dtypes

Total: 29833.859999999997

Nota                  int64
Data                 object
Tomador              object
CNPJ_CPF_Tomador     object
Valor               float64
Empresa              object
Unidade              object
dtype: object

In [142]:
# São Gonçalo Transguard

arquivo = pd.read_excel(r"C:\Users\L_SAR\Documents\Desenv\notas\sao_goncalo\Sao_Goncalo_Transguard.xlsx") # 

# Selecionando as colunas que serão utilizadas:
sao_goncalo_trans = arquivo[["Número", "Data Emissão", "Tomador", "CNPJ Tomador", "Vl. NF."]]

# Apagando linhas em branco:
sao_goncalo_trans = sao_goncalo_trans.dropna(subset=['Número'])

# Criando campos adicionais:
sao_goncalo_trans["Empresa"] = 'Microsoft Corp Inc'
sao_goncalo_trans["Unidade"] = "SÃO GONÇALO - RJ"

# Renomeando os campos para o padrão:
sao_goncalo_trans = sao_goncalo_trans.rename(columns={"Número": "Nota"})
sao_goncalo_trans = sao_goncalo_trans.rename(columns={"Data Emissão": "Data"})
sao_goncalo_trans = sao_goncalo_trans.rename(columns={"Tomador": "Tomador"})
sao_goncalo_trans = sao_goncalo_trans.rename(columns={"CNPJ Tomador": "CNPJ_CPF_Tomador"})
sao_goncalo_trans = sao_goncalo_trans.rename(columns={"Vl. NF.": "Valor"})

# Reordenando colunas:
sao_goncalo_trans = sao_goncalo_trans[['Nota','Data','Tomador','CNPJ_CPF_Tomador','Valor', 'Empresa', 'Unidade']]

# Convertendo tipos de campos:
sao_goncalo_trans["Nota"] = sao_goncalo_trans["Nota"].apply(np.int64) # Converte INT64

# Valor total:
faturamento_sao_goncalo_trans = sao_goncalo_trans["Valor"].sum()

#display(sao_goncalo_trans)

print ("Total:", faturamento_sao_goncalo_trans)

sao_goncalo_trans.dtypes

Total: 202388.71999999997

Nota                  int64
Data                 object
Tomador              object
CNPJ_CPF_Tomador     object
Valor               float64
Empresa              object
Unidade              object
dtype: object

In [143]:
# Senhor do Bonfim

arquivo = pd.read_excel(r"C:\Users\L_SAR\Documents\Desenv\notas\senhor_do_bonfim\Senhor_do_bonfim_Rodando_SPE.xlsx") # 

# Selecionando as colunas que serão utilizadas:
senhor_do_bonfim = arquivo[["Número", "Emissão", "Razão Social", "Tomador", "Total(R$)", "Incidência"]]

# Renomeando campo para que ele não seja renomeado duas vezes:
senhor_do_bonfim = senhor_do_bonfim.rename(columns = {'Tomador' : 'Tomador_senhor_do_bonfim'})

# Apagando linhas em branco:
senhor_do_bonfim = senhor_do_bonfim.dropna(subset=['Número'])

# Criando campos adicionais:
senhor_do_bonfim["Empresa"] = 'Microsoft Corp Inc'

# Renomeando os campos para o padrão:
senhor_do_bonfim = senhor_do_bonfim.rename(columns={"Número": "Nota"})
senhor_do_bonfim = senhor_do_bonfim.rename(columns={"Emissão": "Data"})
senhor_do_bonfim = senhor_do_bonfim.rename(columns={"Razão Social": "Tomador"})
senhor_do_bonfim = senhor_do_bonfim.rename(columns={"Tomador_senhor_do_bonfim": "CNPJ_CPF_Tomador"})
senhor_do_bonfim = senhor_do_bonfim.rename(columns={"Total(R$)": "Valor"})
senhor_do_bonfim = senhor_do_bonfim.rename(columns={"Incidência": "Unidade"})

# Reordenando colunas:
senhor_do_bonfim = senhor_do_bonfim[['Nota','Data','Tomador','CNPJ_CPF_Tomador','Valor', 'Empresa', 'Unidade']]

# Convertendo tipos de campos:
senhor_do_bonfim["Data"] = senhor_do_bonfim["Data"].astype(str)

# Valor total:
faturamento_senhor_do_bonfim = senhor_do_bonfim["Valor"].sum()

#display(senhor_do_bonfim)

print ("Total:", faturamento_senhor_do_bonfim)

senhor_do_bonfim.dtypes

Total: 8840.33

Nota                  int64
Data                 object
Tomador              object
CNPJ_CPF_Tomador     object
Valor               float64
Empresa              object
Unidade              object
dtype: object

In [144]:
# Serra Talhada

arquivo = pd.read_excel(r"C:\Users\L_SAR\Documents\Desenv\notas\serra_talhada\Serra_Talhada.xlsx")  

# Selecionando as colunas que serão utilizadas:
serra_talhada = arquivo[["NF", "Data", "N1", "N2", "N3", "CNPJ", "Valor", "Empresa", "Unidade"]]

# Apagando linhas em branco:
serra_talhada = serra_talhada.dropna(subset=['NF'])

# Renomeando os campos para o padrão:
serra_talhada = serra_talhada.rename(columns={"NF": "Nota"})
serra_talhada = serra_talhada.rename(columns={"Data": "Data"})
serra_talhada = serra_talhada.rename(columns={"CNPJ": "CNPJ_CPF_Tomador"})
serra_talhada = serra_talhada.rename(columns={"Valor": "Valor"})
serra_talhada = serra_talhada.rename(columns={"Empresa": "Empresa"})
serra_talhada = serra_talhada.rename(columns={"Unidade": "Unidade"})

#----------------------------------------------Resolvendo problema campo Tomador----------------------------------------------
# Convertendo tipos de campos:
#serra_talhada["DIA_temp"] = serra_talhada["DIA_temp"].astype(str)

# Criando variável mes e ano:
serra_talhada['Tomador'] = serra_talhada['N1'] + ' ' + serra_talhada['N2'] + ' ' + serra_talhada['N3']

#-----------------------------------------------------------------------------------------------------------------------------

# Reordenando colunas:
serra_talhada = serra_talhada[['Nota','Data','Tomador','CNPJ_CPF_Tomador','Valor', 'Empresa', 'Unidade']]

# Convertendo tipos de campos:
serra_talhada["Nota"] = serra_talhada["Nota"].apply(np.int64) # Converte INT64
serra_talhada["Data"] = serra_talhada["Data"].astype(str)
serra_talhada["CNPJ_CPF_Tomador"] = serra_talhada["CNPJ_CPF_Tomador"].astype(str)

# Valor total:
faturamento_serra_talhada = serra_talhada["Valor"].sum()

#display(serra_talhada)

print ("Total:", faturamento_serra_talhada)

serra_talhada.dtypes

Total: 6937.8

Nota                  int64
Data                 object
Tomador              object
CNPJ_CPF_Tomador     object
Valor               float64
Empresa              object
Unidade              object
dtype: object

In [145]:
# Tanguá Nova RL

arquivo = pd.read_excel(r"C:\Users\L_SAR\Documents\Desenv\notas\tangua_nova_rl\Tangua_Nova_RL.xls")

#----------------------------------------------------MUDAR ORDEM DA DATA----------------------------------------------------

# Apagando linhas em branco:
arquivo = arquivo.dropna(subset = "Nota Fiscal")

# Convertendo campo Dia:
arquivo["Dia"] = arquivo["Dia"].apply(np.int64)

# Fazendo slice do campo competência para separar as partes:
mes_temp = arquivo["Competência"].str.slice(start = 6)
ano_temp = arquivo["Competência"].str.slice(start = 0, stop = 4)
barra_temp = arquivo["Competência"].str.slice(start = 4, stop = 5)

# Juntando as partes:
arquivo["Competência"] = (barra_temp) + (mes_temp) + (barra_temp) + (ano_temp)

#---------------------------------------------------------------------------------------------------------------------------

# Selecionando as colunas que serão utilizadas:
tangua_nova_rl = arquivo[["Nota Fiscal", "Dia", "Competência", "CPF/CNPJ - Tomador/Prestador", "Vr.NF"]]

# Criando campos adicionais:
tangua_nova_rl["Empresa"] = "Tanguá Nova RL"
tangua_nova_rl["Unidade"] = "Tanguá Nova RL"

# Renomeando os campos para o padrão:
tangua_nova_rl = tangua_nova_rl.rename(columns={"Nota Fiscal": "Nota"})
tangua_nova_rl = tangua_nova_rl.rename(columns={"CPF/CNPJ - Tomador/Prestador": "CNPJ_CPF_Tomador"})
tangua_nova_rl = tangua_nova_rl.rename(columns={"Vr.NF": "Valor"})

#----------------------------------------------------CRIANDO CAMPO DATA----------------------------------------------------

# Convertendo tipos de campos:
tangua_nova_rl["Dia"] = tangua_nova_rl["Dia"].astype(str)
tangua_nova_rl["Competência"] = tangua_nova_rl["Competência"].astype(str)

# Criando campo "Data"
tangua_nova_rl["Data"] = tangua_nova_rl["Dia"] + tangua_nova_rl["Competência"]

#---------------------------------------------------------------------------------------------------------------------------

# Reordenando colunas:
tangua_nova_rl = tangua_nova_rl[['Nota','Data', 'CNPJ_CPF_Tomador','Valor', 'Empresa', 'Unidade']]

# Convertendo tipos de campos:
tangua_nova_rl["Nota"] = tangua_nova_rl["Nota"].apply(np.int64) # Converte INT64
tangua_nova_rl["CNPJ_CPF_Tomador"] = tangua_nova_rl["CNPJ_CPF_Tomador"].astype(str)

# Valor total:
faturamento_tangua_nova_rl = tangua_nova_rl["Valor"].sum()

display(tangua_nova_rl)

print ("Total:", faturamento_tangua_nova_rl)

tangua_nova_rl.dtypes

C:\Users\L_SAR\AppData\Local\Temp\ipykernel_13500\1366292596.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tangua_nova_rl["Empresa"] = "Tanguá Nova RL"
C:\Users\L_SAR\AppData\Local\Temp\ipykernel_13500\1366292596.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tangua_nova_rl["Unidade"] = "Tanguá Nova RL"

,Nota,Data,CNPJ_CPF_Tomador,Valor,Empresa,Unidade
1,19310,4/7/2022,1457320703.0,202.26,Tanguá Nova RL,Tanguá Nova RL
4,19311,5/7/2022,1457320703.0,467.16,Tanguá Nova RL,Tanguá Nova RL
7,19312,7/7/2022,7538895795.0,337.10,Tanguá Nova RL,Tanguá Nova RL
10,19313,7/7/2022,7538895795.0,459.76,Tanguá Nova RL,Tanguá Nova RL
13,19314,7/7/2022,15214634765.0,632.80,Tanguá Nova RL,Tanguá Nova RL
16,19315,7/7/2022,15214634765.0,450.20,Tanguá Nova RL,Tanguá Nova RL
19,19316,7/7/2022,10949705730.0,301.49,Tanguá Nova RL,Tanguá Nova RL
22,19317,7/7/2022,10949705730.0,85.56,Tanguá Nova RL,Tanguá Nova RL
25,19318,7/7/2022,1955378746.0,632.80,Tanguá Nova RL,Tanguá Nova RL
28,19319,7/7/2022,1955378746.0,543.75,Tanguá Nova RL,Tanguá Nova RL
31,19320,7/7/2022,14168808793.0,582.53,Tanguá Nova RL,Tanguá Nova RL
34,19321,7/7/2022,14168808793.0,433.75,Tanguá Nova RL,Tanguá Nova RL
37,19322,8/7/2022,14695040735.0,202.26,Tanguá Nova RL,Tanguá Nova RL
40,19323,8/7/2022,14695040735.0,459.76,Tanguá Nova RL,Tanguá Nova RL
43,19324,11/7/2022,3061476709.0,134.84,Tanguá Nova RL,Tanguá Nova RL
46,19325,11/7/2022,3061476709.0,463.80,Tanguá Nova RL,Tanguá Nova RL
49,19326,11/7/2022,4252109523.0,741.62,Tanguá Nova RL,Tanguá Nova RL
52,19327,11/7/2022,4252109523.0,471.30,Tanguá Nova RL,Tanguá Nova RL
55,19328,12/7/2022,9935465799.0,337.10,Tanguá Nova RL,Tanguá Nova RL
58,19329,12/7/2022,9935465799.0,459.76,Tanguá Nova RL,Tanguá Nova RL
61,19330,12/7/2022,82532826720.0,134.84,Tanguá Nova RL,Tanguá Nova RL
64,19331,12/7/2022,82532826720.0,463.80,Tanguá Nova RL,Tanguá Nova RL
67,19332,12/7/2022,82942617772.0,199.70,Tanguá Nova RL,Tanguá Nova RL
70,19333,12/7/2022,82942617772.0,433.75,Tanguá Nova RL,Tanguá Nova RL
73,19334,13/7/2022,90295331704.0,433.75,Tanguá Nova RL,Tanguá Nova RL
76,19335,14/7/2022,90295331704.0,632.80,Tanguá Nova RL,Tanguá Nova RL
79,19336,14/7/2022,10779458761.0,158.20,Tanguá Nova RL,Tanguá Nova RL
82,19337,14/7/2022,10779458761.0,429.35,Tanguá Nova RL,Tanguá Nova RL
85,19338,19/7/2022,15849115730.0,269.68,Tanguá Nova RL,Tanguá Nova RL
88,19339,20/7/2022,15849115730.0,459.76,Tanguá Nova RL,Tanguá Nova RL
91,19340,20/7/2022,9492441713.0,1154.10,Tanguá Nova RL,Tanguá Nova RL
94,19341,20/7/2022,9492441713.0,429.35,Tanguá Nova RL,Tanguá Nova RL
97,19342,20/7/2022,1764213785.0,230.82,Tanguá Nova RL,Tanguá Nova RL
100,19343,20/7/2022,1764213785.0,433.75,Tanguá Nova RL,Tanguá Nova RL
103,19344,20/7/2022,14378979756.0,539.36,Tanguá Nova RL,Tanguá Nova RL
106,19345,20/7/2022,14378979756.0,459.76,Tanguá Nova RL,Tanguá Nova RL
109,19346,21/7/2022,597467773.0,471.94,Tanguá Nova RL,Tanguá Nova RL
112,19347,21/7/2022,597467773.0,463.80,Tanguá Nova RL,Tanguá Nova RL
115,19348,25/7/2022,12799012760.0,459.76,Tanguá Nova RL,Tanguá Nova RL
118,19349,25/7/2022,5218130770.0,67.42,Tanguá Nova RL,Tanguá Nova RL
121,19350,25/7/2022,5218130770.0,463.80,Tanguá Nova RL,Tanguá Nova RL
124,19351,25/7/2022,10830033726.0,1582.00,Tanguá Nova RL,Tanguá Nova RL
127,19352,25/7/2022,10830033726.0,433.75,Tanguá Nova RL,Tanguá Nova RL
130,19353,25/7/2022,7421289704.0,389.02,Tanguá Nova RL,Tanguá Nova RL
133,19354,25/7/2022,7421289704.0,433.75,Tanguá Nova RL,Tanguá Nova RL
136,19355,27/7/2022,12799012760.0,337.10,Tanguá Nova RL,Tanguá Nova RL
139,19356,27/7/2022,12799012760.0,337.10,Tanguá Nova RL,Tanguá Nova RL
142,19357,27/7/2022,12252200766.0,202.26,Tanguá Nova RL,Tanguá Nova RL
145,19358,27/7/2022,12252200766.0,463.80,Tanguá Nova RL,Tanguá Nova RL
148,19359,28/7/2022,1774912724.0,463.80,Tanguá Nova RL,Tanguá Nova RL
151,19360,28/7/2022,1774912724.0,67.42,Tanguá Nova RL,Tanguá Nova RL
154,19361,29/7/2022,14449111710.0,2564.94,Tanguá Nova RL,Tanguá Nova RL
157,19362,29/7/2022,14449111710.0,433.75,Tanguá Nova RL,Tanguá Nova RL
160,19363,29/7/2022,950563781.0,134.84,Tanguá Nova RL,Tanguá Nova RL
163,19364,29/7/2022,950563781.0,463.80,Tanguá Nova RL,Tanguá Nova RL

Total: 25496.419999999995

Nota                  int64
Data                 object
CNPJ_CPF_Tomador     object
Valor               float64
Empresa              object
Unidade              object
dtype: object

In [146]:
# Tanguá Transguard

arquivo = pd.read_excel(r"C:\Users\L_SAR\Documents\Desenv\notas\tangua_transguard\Tangua_Transguard.xls")  

#----------------------------------------------------MUDAR ORDEM DA DATA----------------------------------------------------

# Apagando linhas em branco:
arquivo = arquivo.dropna(subset = "Nota Fiscal")

# Convertendo campo Dia:
arquivo["Dia"] = arquivo["Dia"].apply(np.int64)

# Fazendo slice do campo competência para separar as partes:
mes_temp = arquivo["Competência"].str.slice(start = 6)
ano_temp = arquivo["Competência"].str.slice(start = 0, stop = 4)
barra_temp = arquivo["Competência"].str.slice(start = 4, stop = 5)

# Juntando as partes:
arquivo["Competência"] = (barra_temp) + (mes_temp) + (barra_temp) + (ano_temp)

#---------------------------------------------------------------------------------------------------------------------------

# Selecionando as colunas que serão utilizadas:
tangua_transguard = arquivo[["Nota Fiscal", "Dia", "Competência", "Nome do Tomador/Prestador", "CPF/CNPJ - Tomador/Prestador", "Vr.NF"]]

# Criando campos adicionais:
tangua_transguard["Empresa"] = "Tanguá Transguard"
tangua_transguard["Unidade"] = "Tanguá Transguard"

# Renomeando os campos para o padrão:
tangua_transguard = tangua_transguard.rename(columns={"Nota Fiscal": "Nota"})
tangua_transguard = tangua_transguard.rename(columns={"Nome do Tomador/Prestador": "Tomador"})
tangua_transguard = tangua_transguard.rename(columns={"CPF/CNPJ - Tomador/Prestador": "CNPJ_CPF_Tomador"})
tangua_transguard = tangua_transguard.rename(columns={"Vr.NF": "Valor"})

#----------------------------------------------------CRIANDO CAMPO DATA----------------------------------------------------

# Convertendo tipos de campos:
tangua_transguard["Dia"] = tangua_transguard["Dia"].astype(str)
tangua_transguard["Competência"] = tangua_transguard["Competência"].astype(str)

# Criando campo "Data"
tangua_transguard["Data"] = tangua_transguard["Dia"] + tangua_transguard["Competência"]

#---------------------------------------------------------------------------------------------------------------------------

# Reordenando colunas:
tangua_transguard = tangua_transguard[['Nota','Data','Tomador','CNPJ_CPF_Tomador','Valor', 'Empresa', 'Unidade']]

# Convertendo tipos de campos:
tangua_transguard["Nota"] = tangua_transguard["Nota"].apply(np.int64) # Converte INT64
tangua_transguard["CNPJ_CPF_Tomador"] = tangua_transguard["CNPJ_CPF_Tomador"].astype(str)

# Valor total:
faturamento_tangua_transguard = tangua_transguard["Valor"].sum()

display(tangua_transguard)

print ("Total:", faturamento_tangua_transguard)

tangua_transguard.dtypes

C:\Users\L_SAR\AppData\Local\Temp\ipykernel_13500\322472443.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tangua_transguard["Empresa"] = "Tanguá Transguard"
C:\Users\L_SAR\AppData\Local\Temp\ipykernel_13500\322472443.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tangua_transguard["Unidade"] = "Tanguá Transguard"

,Nota,Data,Tomador,CNPJ_CPF_Tomador,Valor,Empresa,Unidade
0,145,1/7/2022,MATHEUS DE OLIVEIRA SILVA,15345245762.0,213.84,Tanguá Transguard,Tanguá Transguard
1,146,1/7/2022,MATHEUS DE OLIVEIRA SILVA,15345245762.0,88.30,Tanguá Transguard,Tanguá Transguard
2,147,4/7/2022,ADRIANE APARECIDA MARTINS ARAUJO,2306655782.0,525.60,Tanguá Transguard,Tanguá Transguard
3,148,5/7/2022,ROLBERIO NUNES FERREIRA,14430997756.0,170.63,Tanguá Transguard,Tanguá Transguard
4,149,5/7/2022,ROLBERIO NUNES FERREIRA,14430997756.0,233.60,Tanguá Transguard,Tanguá Transguard
...,...,...,...,...,...,...,...
64,209,26/7/2022,LUIZ RICARDO R. DA SILVA,13611144797.0,700.80,Tanguá Transguard,Tanguá Transguard
65,210,28/7/2022,ELIELTON FLORINDO DA SILVA,11391043731.0,88.30,Tanguá Transguard,Tanguá Transguard
66,211,28/7/2022,ELIELTON FLORINDO DA SILVA,11391043731.0,106.92,Tanguá Transguard,Tanguá Transguard
67,212,28/7/2022,PEDRO HENRIQUE DAMIANI,12916720790.0,170.63,Tanguá Transguard,Tanguá Transguard
68,213,28/7/2022,PEDRO HENRIQUE DAMIANI,12916720790.0,175.20,Tanguá Transguard,Tanguá Transguard

Total: 11146.089999999997

Nota                  int64
Data                 object
Tomador              object
CNPJ_CPF_Tomador     object
Valor               float64
Empresa              object
Unidade              object
dtype: object

In [147]:
# Teixeira de Freitas Transguard Nordeste

arquivo = pd.read_excel(r"C:\Users\L_SAR\Documents\Desenv\notas\teixeira_de_freitas_transguard_nordeste\Teixeira_de_freitas_Transguard_Nordeste.xlsx")  

# Selecionando as colunas que serão utilizadas:
teixeira_de_freitas_trans = arquivo[["ns1:Numero", "ns1:DataEmissao", "ns1:RazaoSocial17", "ns1:Cpf", "ns1:ValorServicos", "ns1:RazaoSocial"]]

# Apagando linhas em branco:
teixeira_de_freitas_trans = teixeira_de_freitas_trans.dropna(subset=['ns1:Numero'])

# Criando campos adicionais:
teixeira_de_freitas_trans["Unidade"] = "Teixeira de Freitas Transguard Nordeste"

# Renomeando os campos para o padrão:
teixeira_de_freitas_trans = teixeira_de_freitas_trans.rename(columns={"ns1:Numero": "Nota"})
teixeira_de_freitas_trans = teixeira_de_freitas_trans.rename(columns={"ns1:DataEmissao": "Data"})
teixeira_de_freitas_trans = teixeira_de_freitas_trans.rename(columns={"ns1:RazaoSocial17": "Tomador"})
teixeira_de_freitas_trans = teixeira_de_freitas_trans.rename(columns={"ns1:Cpf": "CNPJ_CPF_Tomador"})
teixeira_de_freitas_trans = teixeira_de_freitas_trans.rename(columns={"ns1:ValorServicos": "Valor"})
teixeira_de_freitas_trans = teixeira_de_freitas_trans.rename(columns={"ns1:RazaoSocial": "Empresa"})

# Reordenando colunas:
teixeira_de_freitas_trans = teixeira_de_freitas_trans[['Nota','Data','Tomador','CNPJ_CPF_Tomador','Valor', 'Empresa', 'Unidade']]

# Convertendo tipos de campos:
teixeira_de_freitas_trans["Nota"] = teixeira_de_freitas_trans["Nota"].apply(np.int64) # Converte INT64
teixeira_de_freitas_trans["Data"] = teixeira_de_freitas_trans["Data"].astype(str)
teixeira_de_freitas_trans["CNPJ_CPF_Tomador"] = teixeira_de_freitas_trans["CNPJ_CPF_Tomador"].astype(str)

# Valor total:
faturamento_teixeira_de_freitas_trans = teixeira_de_freitas_trans["Valor"].sum()

#display(teixeira_de_freitas_trans)

print ("Total:", faturamento_teixeira_de_freitas_trans)

teixeira_de_freitas_trans.dtypes

Total: 61540.38

Nota                  int64
Data                 object
Tomador              object
CNPJ_CPF_Tomador     object
Valor               float64
Empresa              object
Unidade              object
dtype: object

In [148]:
# Três Rios - Nova RL

arquivo = pd.read_excel(r"C:\Users\L_SAR\Documents\Desenv\notas\tres_rios_nova_rl\Tres Rios - Nova RL.xlsx")  

#----------------------------------------------------SEPARAR CPF E TOMADOR----------------------------------------------------

# Apagando linhas em branco:
arquivo = arquivo.dropna(subset = "NF")

# Fazendo slice do campo tomador para compor o campo CPF:
tomador_temp = arquivo["Tomador"].str.slice(start = 17)
cpf_temp = arquivo["Tomador"].str.slice(start = 0, stop = 14)

# Criando campos para separar os dados:
arquivo["Tomador"] = (tomador_temp)
arquivo["CNPJ_CPF_Tomador"] = (cpf_temp)

#-----------------------------------------------------------------------------------------------------------------------------

# Selecionando as colunas que serão utilizadas:
tres_rios_nova_rl = arquivo[["NF", "Dt.Emissão", "Tomador", "CNPJ_CPF_Tomador", "Valor", "Execução"]]

# Apagando linhas em branco:
tres_rios_nova_rl = tres_rios_nova_rl.dropna(subset=['NF'])

# Criando campos adicionais:
tres_rios_nova_rl["Empresa"] = "Três Rios - Nova RL"
    
# Renomeando os campos para o padrão:
tres_rios_nova_rl = tres_rios_nova_rl.rename(columns={"NF": "Nota"})
tres_rios_nova_rl = tres_rios_nova_rl.rename(columns={"Dt.Emissão": "Data"})
tres_rios_nova_rl = tres_rios_nova_rl.rename(columns={"Tomador": "Tomador"})
tres_rios_nova_rl = tres_rios_nova_rl.rename(columns={"CNPJ_CPF_Tomador": "CNPJ_CPF_Tomador"})
tres_rios_nova_rl = tres_rios_nova_rl.rename(columns={"Valor": "Valor"})
tres_rios_nova_rl = tres_rios_nova_rl.rename(columns={"Execução": "Unidade"})

# Reordenando colunas:
tres_rios_nova_rl = tres_rios_nova_rl[['Nota', 'Data', 'Tomador', 'CNPJ_CPF_Tomador', 'Valor', 'Empresa', 'Unidade']]

# Convertendo tipos de campos:
#tres_rios_nova_rl[""] = tres_rios_nova_rl[""].apply(np.int64) # Converte INT64
tres_rios_nova_rl["Data"] = tres_rios_nova_rl["Data"].astype(str)

# Valor total:
faturamento_tres_rios_nova_rl = tres_rios_nova_rl["Valor"].sum()

#display(tres_rios_nova_rl)

print ("Total:", faturamento_tres_rios_nova_rl)

tres_rios_nova_rl.dtypes

Total: 24655.21

Nota                  int64
Data                 object
Tomador              object
CNPJ_CPF_Tomador     object
Valor               float64
Empresa              object
Unidade              object
dtype: object

In [149]:
# Três Rios - Transguard

arquivo = pd.read_excel(r"C:\Users\L_SAR\Documents\Desenv\notas\tres_rios_transguard\Tres Rios - Transguard.xlsx")  

#----------------------------------------------------SEPARAR CPF E TOMADOR----------------------------------------------------

# Apagando linhas em branco:
arquivo = arquivo.dropna(subset = "NF")

# Fazendo slice do campo tomador para compor o campo CPF:
tomador_temp = arquivo["Tomador"].str.slice(start = 17)
cpf_temp = arquivo["Tomador"].str.slice(start = 0, stop = 14)

# Criando campos para separar os dados:
arquivo["Tomador"] = (tomador_temp)
arquivo["CNPJ_CPF_Tomador"] = (cpf_temp)

#-----------------------------------------------------------------------------------------------------------------------------

# Selecionando as colunas que serão utilizadas:
tres_rios_nova_trans = arquivo[["NF", "Dt.Emissão", "Tomador", "CNPJ_CPF_Tomador", "Valor", "Execução"]]

# Apagando linhas em branco:
tres_rios_nova_trans = tres_rios_nova_trans.dropna(subset=['NF'])

# Criando campos adicionais:
tres_rios_nova_trans["Empresa"] = "Três Rios - Transguard"
    

# Renomeando os campos para o padrão:
tres_rios_nova_trans = tres_rios_nova_trans.rename(columns={"NF": "Nota"})
tres_rios_nova_trans = tres_rios_nova_trans.rename(columns={"Dt.Emissão": "Data"})
tres_rios_nova_trans = tres_rios_nova_trans.rename(columns={"Tomador": "Tomador"})
tres_rios_nova_trans = tres_rios_nova_trans.rename(columns={"CNPJ_CPF_Tomador": "CNPJ_CPF_Tomador"})
tres_rios_nova_trans = tres_rios_nova_trans.rename(columns={"Valor": "Valor"})
tres_rios_nova_trans = tres_rios_nova_trans.rename(columns={"Execução": "Unidade"})

# Reordenando colunas:
tres_rios_nova_trans = tres_rios_nova_trans[['Nota','Data','Tomador','CNPJ_CPF_Tomador','Valor', 'Empresa', 'Unidade']]

# Convertendo tipos de campos:
#tres_rios_nova_trans[""] = tres_rios_nova_trans[""].apply(np.int64) # Converte INT64
tres_rios_nova_trans["Data"] = tres_rios_nova_trans["Data"].astype(str)

# Valor total:
faturamento_tres_rios_nova_trans = tres_rios_nova_trans["Valor"].sum()

#display(tres_rios_nova_trans)

print ("Total:", faturamento_tres_rios_nova_trans)

tres_rios_nova_trans.dtypes

Total: 19313.839999999997

Nota                  int64
Data                 object
Tomador              object
CNPJ_CPF_Tomador     object
Valor               float64
Empresa              object
Unidade              object
dtype: object

# Merge das prefeituras:

In [150]:
# Barra do Piraí Transguard + Caicó Transguard:

df_merge = pd.merge(barra_pirai, caico, how = 'outer')

In [151]:
# + Caruaru Transguard

df_merge = pd.merge(df_merge, caruaru, how = 'outer')

In [152]:
# + Ceilândia Transguard

df_merge = pd.merge(df_merge, ceilandia, how = 'outer')

In [153]:
# + Coité SPE

df_merge = pd.merge(df_merge, coite, how = 'outer')

In [154]:
# + Cuiabá Nova

df_merge = pd.merge(df_merge, cuiaba, how = 'outer')

In [155]:
# + Itabuna Transguarde Nordeste

df_merge = pd.merge(df_merge, itabuna, how = 'outer')

In [156]:
# + Itaguaí Transguard

df_merge = pd.merge(df_merge, itaguai_trans, how = 'outer')

In [157]:
# + Itaperuna Nova RL

df_merge = pd.merge(df_merge, itaperuna_nova_rl, how = 'outer')

In [158]:
# + Maceió Transguard

df_merge = pd.merge(df_merge, maceio_trans, how = 'outer')

In [159]:
# + Magé Nova RL

df_merge = pd.merge(df_merge, mage_nova_rl, how = 'outer')

In [160]:
# + Magé Transguard

df_merge = pd.merge(df_merge, mage_transguard, how = 'outer')

In [161]:
# + Mossoró Transguard

df_merge = pd.merge(df_merge, mossoro_trans, how = 'outer')

In [162]:
# + Natal Transguard

df_merge = pd.merge(df_merge, natal_trans, how = 'outer')

In [163]:
# + Petrolina RL

df_merge = pd.merge(df_merge, petrolina_rl, how = 'outer')

In [164]:
# + Salgueiro Transguard

df_merge = pd.merge(df_merge, salgueiro_trans, how = 'outer')

In [165]:
# + São Caetano Nova RL

df_merge = pd.merge(df_merge, sao_caetano_nova_rl, how = 'outer')

In [166]:
# + São Gonçalo Transguard

df_merge = pd.merge(df_merge, sao_goncalo_trans, how = 'outer')

In [167]:
# + Senhor do Bonfim

df_merge = pd.merge(df_merge, senhor_do_bonfim, how = 'outer')

In [168]:
# + Serra Talhada

df_merge = pd.merge(df_merge, serra_talhada, how = 'outer')

In [169]:
# + Tanguá Nova RL

df_merge = pd.merge(df_merge, tangua_nova_rl, how = 'outer')

In [170]:
# + Tanguá Transguard

df_merge = pd.merge(df_merge, tangua_transguard, how = 'outer')

In [171]:
# + Teixeira de Freitas Transguard

df_merge = pd.merge(df_merge, teixeira_de_freitas_trans, how = 'outer')

In [172]:
# + Três Rios Nova RL

df_merge = pd.merge(df_merge, tres_rios_nova_rl, how = 'outer')

In [173]:
# + Três Rios Transguard

df_merge = pd.merge(df_merge, tres_rios_nova_trans, how = 'outer')

In [174]:
# Valor total prefeituras:
faturamento_df_merge = df_merge["Valor"].sum()

print ("Total:", faturamento_df_merge)

df_merge.dtypes

Total: 1240007.2

Nota                  int64
Data                 object
Tomador              object
CNPJ_CPF_Tomador     object
Valor               float64
Empresa              object
Unidade              object
dtype: object

In [175]:
filename = r'C:\Users\L_SAR\Documents\Desenv\notas\prefeituras.xlsx'
df_merge.to_excel(filename, sheet_name='merged', index=False)

# Base vs Prefeituras:

In [176]:
dif = base_sistema.merge(df_merge, on=['Nota', 'Unidade'], how='outer', suffixes=['', '_'], indicator=True)
display(dif)

,Nota,Data,Tomador,CNPJ_CPF_Tomador,Valor,Empresa,Unidade,Data_,Tomador_,CNPJ_CPF_Tomador_,Valor_,Empresa_,_merge
0,16385,01/07/2022,MARIA CLARA ROSENO DA SILVA (113523) ...,103.254.424-44,71.30,TRANSGUARD DO BRASIL REMOCAO E ACAUTELAMENTO D...,MACEIÓ,NaN,NaN,NaN,NaN,NaN,left_only
1,16386,01/07/2022,MARIA CLARA ROSENO DA SILVA (113523) ...,103.254.424-44,220.74,TRANSGUARD DO BRASIL REMOCAO E ACAUTELAMENTO D...,MACEIÓ,NaN,NaN,NaN,NaN,NaN,left_only
2,16387,01/07/2022,SANDRA GOMES DE ANDRADE PROTASIO (113530) ...,700.565.604-00,71.30,TRANSGUARD DO BRASIL REMOCAO E ACAUTELAMENTO D...,MACEIÓ,NaN,NaN,NaN,NaN,NaN,left_only
3,16388,01/07/2022,SANDRA GOMES DE ANDRADE PROTASIO (113530) ...,700.565.604-00,220.74,TRANSGUARD DO BRASIL REMOCAO E ACAUTELAMENTO D...,MACEIÓ,NaN,NaN,NaN,NaN,NaN,left_only
4,16391,04/07/2022,JOSE IBIS TORRES (114087) ...,057.589.384-24,34.08,TRANSGUARD DO BRASIL REMOCAO E ACAUTELAMENTO D...,MACEIÓ,NaN,NaN,NaN,NaN,NaN,left_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9424,168,NaN,NaN,NaN,NaN,NaN,Três Rios/RJ,2022-07-26,Claudio Luis Sil,927.289.956-72,262.23,Três Rios - Transguard,right_only
9425,169,NaN,NaN,NaN,NaN,NaN,Três Rios/RJ,2022-07-27,Ramon De Oliveir,128.880.987-50,173.33,Três Rios - Transguard,right_only
9426,170,NaN,NaN,NaN,NaN,NaN,Três Rios/RJ,2022-07-27,Ramon De Oliveir,128.880.987-50,108.54,Três Rios - Transguard,right_only
9427,171,NaN,NaN,NaN,NaN,NaN,Três Rios/RJ,2022-07-28,Marlon Ramos De,185.198.127-67,179.48,Três Rios - Transguard,right_only
9428,172,NaN,NaN,NaN,NaN,NaN,Três Rios/RJ,2022-07-28,Marlon Ramos De,185.198.127-67,325.62,Três Rios - Transguard,right_only

In [177]:
# Indexando:
apaga_ambos = dif[ dif['_merge'] == 'right_only' ].index
apaga_left = dif[ dif['_merge'] == 'left_only' ].index

# Apagar essas linhas do Dataframe:
dif.drop(apaga_ambos, inplace = True)
dif.drop(apaga_left, inplace = True)

display(dif)

Empty DataFrame
Columns: [Nota, Data, Tomador, CNPJ_CPF_Tomador, Valor, Empresa, Unidade, Data_, Tomador_, CNPJ_CPF_Tomador_, Valor_, Empresa_, _merge]
Index: []

In [178]:
# Valor total prefeituras:
faturamento_dif = dif["Valor_"].sum()

print ("Total:", faturamento_dif)

dif.dtypes

Total: 0.0

Nota                    int64
Data                   object
Tomador                object
CNPJ_CPF_Tomador       object
Valor                 float64
Empresa                object
Unidade                object
Data_                  object
Tomador_               object
CNPJ_CPF_Tomador_      object
Valor_                float64
Empresa_               object
_merge               category
dtype: object